import { sovereignStorage } from '../swarm/core/storage.js';
import fs from 'fs/promises';
import path from 'path';
import { FileSystemTool } from '../swarm/tools/filesystem.js';

interface SwarmState {
    last_updated: string;
    ci: { status: string; last_green_sha?: string; last_fail_reason?: string; build_duration?: string };
    curiosity: { findings: any[]; last_scan: string };
    evolution: { last_score: number; trend: string; greenlit: boolean };
    frontend_qa: { status: string; failures: any[] };
    swarm: { last_commit_sha: string; last_task: string; status: string };
    orchestrator: { next_action: string; reason: string };
}

async function run() {
    const mode = process.argv[2] || 'ORCHESTRATE';
    console.log(`🚀 [CI Manager] Mode: ${mode}`);

    try {
        switch (mode) {
            case 'REPORT':
                await reportMetrics();
                break;
            case 'ORCHESTRATE':
                await orchestrate();
                break;
            case 'DASHBOARD':
                await generateDashboard();
                break;
            default:
                console.error(`Unknown mode: ${mode}`);
                process.exit(1)
        }
    } catch (err) {
        console.error(`❌ [CI Manager] Critical Failure:`, err);
        process.exit(1);
    }
}

/**
 * Generates the status dashboard (SWARM_STATUS.md)
 */
async function generateDashboard() {
    const wrapper = await sovereignStorage.load();
    const state = wrapper ? wrapper.state as SwarmState : createDefaultState();
    const todo = await fs.readFile('TODO.md', 'utf8').catch(() => '');

    // Extract Phase Progress from TODO.md
    const phases = todo.match(/## (Phase \d+:[^ \n]+)/g) || [];
    const currentPhase = phases[phases.length - 1] || 'Phase 1: Stability';

    const md = `# AppForge Swarm Live Status
    
## 🚀 Current Engineering Phase
**${currentPhase}** (Synced from [TODO.md](TODO.md))

## 📊 Performance & Health
- **CI Status**: ${state.ci.status === 'pass' ? '✅ GREEN' : '❌ FAIL'}
- **Evolution Score**: ${state.evolution.last_score || 'N/A'}
- **Frontend QA**: ${state.frontend_qa.status || 'N/A'}

## 🧠 Strategic Oracle
- **Next Decision**: \`${state.orchestrator.next_action}\`
- **Logic Reason**: ${state.orchestrator.reason}

## 🏗️ Build Telemetry
- **Last Sync**: ${new Date(state.last_updated).toLocaleString()}
- **Build Dur**: ${state.ci.build_duration || 'N/A'}

---
*Status generated by Sovereign CI Manager*
`;

    await fs.writeFile('SWARM_STATUS.md', md);
    console.log('📝 [CI Manager] SWARM_STATUS.md updated.');
}

/**
 * Reports detailed metrics from a standard CI run (node.js.yml)
 */
async function reportMetrics() {
    const metricsPath = 'src/data/frontend_metrics.json';
    let metrics = { errorCount: 0, avgLatency: 0, lastFlush: new Date().toISOString(), topErrors: [] };

    try {
        const raw = await fs.readFile(metricsPath, 'utf8');
        metrics = JSON.parse(raw);
    } catch { }

    // In a real CI environment, we would parse test/lint results here
    // For now, we update the timestamp and basic health
    metrics.lastFlush = new Date().toISOString();

    await fs.writeFile(metricsPath, JSON.stringify(metrics, null, 2));
    console.log(`📊 [CI Manager] Telemetry reported to ${metricsPath}`);

    // Update Sovereign State via Upstash
    const wrapper = await sovereignStorage.load();
    if (wrapper && wrapper.state) {
        const state = wrapper.state as SwarmState;
        state.ci = state.ci || ({} as any);
        state.ci.status = 'pass';
        state.ci.last_green_sha = process.env.GITHUB_SHA || '';
        await sovereignStorage.save({
            ...wrapper,
            timestamp: new Date().toISOString(),
            state: state
        });
    }
}

/**
 * Handles the main orchestration loop formerly in Python
 */
async function orchestrate() {
    const fsTool = new FileSystemTool();
    const wrapper = await sovereignStorage.load();
    let state = wrapper ? wrapper.state as SwarmState : createDefaultState();

    const trigger = process.env.TRIGGER || 'manual';
    const workflowName = process.env.WORKFLOW_NAME || '';
    const conclusion = process.env.CONCLUSION || '';

    console.log(`🧠 [CI Manager] Trigger: ${trigger} | Workflow: ${workflowName} | Conclusion: ${conclusion}`);

    // 1. Merge Artifacts (if any)
    const artifactsDir = 'agent_outputs';
    try {
        const files = await fsTool.listFiles(`${artifactsDir}/**/*.json`);
        for (const file of files) {
            console.log(`   📂 Reading artifact: ${file}`);
            const data = JSON.parse(await fs.readFile(file, 'utf8'));
            const agentType = data.agent_type;
            if (agentType && (state as any)[agentType]) {
                console.log(`   📎 Merging artifact from ${agentType}`);
                Object.assign((state as any)[agentType], data.payload);
            }
        }
    } catch (err) {
        console.log('   ℹ️ No artifacts found or merge failed.');
    }

    // 2. Event Context Logic
    if (workflowName.includes('Node.js CI') || workflowName.includes('Iron Brain')) {
        state.ci.status = conclusion === 'success' ? 'pass' : 'fail';
        if (conclusion !== 'success') state.ci.last_fail_reason = `${workflowName} failed`;
    } else if (workflowName.includes('Frontend QA')) {
        state.frontend_qa.status = conclusion === 'success' ? 'pass' : 'fail';
    }

    // 3. Decide Next Action (Decision Matrix)
    let nextAction = 'none';
    let reason = 'All systems nominal';

    if (process.env.FORCE_ACTION) {
        nextAction = process.env.FORCE_ACTION;
        reason = 'Manually forced';
    } else if (conclusion === 'failure') {
        nextAction = 'autonomous_swarm';
        reason = `Workflow ${workflowName} failed. CI healer engaged.`;
    } else if (state.ci.status === 'fail') {
        nextAction = 'autonomous_swarm';
        reason = `CI failure: ${state.ci.last_fail_reason}`;
    } else if (state.frontend_qa.status === 'fail') {
        nextAction = 'frontend_qa_swarm';
        reason = 'Frontend QA failures detected';
    } else if (state.evolution.greenlit && state.ci.status === 'pass') {
        nextAction = 'quantum_evolution';
        reason = 'CI green, evolution proceeding';
    } else if (trigger === 'schedule') {
        nextAction = 'curiosity_scan';
        reason = 'Scheduled curiosity pulse';
    }

    state.orchestrator = { next_action: nextAction, reason };
    state.last_updated = new Date().toISOString();

    // 4. Save State (Wrapped)
    await sovereignStorage.save({
        timestamp: new Date().toISOString(),
        version: '2.0.0',
        state: state
    });

    // 5. Output for GitHub Actions
    if (process.env.GITHUB_OUTPUT) {
        await fs.appendFile(process.env.GITHUB_OUTPUT, `next_action=${nextAction}\n`);
        await fs.appendFile(process.env.GITHUB_OUTPUT, `reason=${reason}\n`);
        const taskDesc = nextAction === 'autonomous_swarm' ? `Fix: ${state.ci.last_fail_reason}` : reason;
        await fs.appendFile(process.env.GITHUB_OUTPUT, `task=${taskDesc}\n`);
    }

    console.log(`🎯 [CI Manager] Decision: ${nextAction} (${reason})`);
}

function createDefaultState(): SwarmState {
    return {
        last_updated: new Date().toISOString(),
        ci: { status: 'unknown' },
        curiosity: { findings: [], last_scan: '' },
        evolution: { last_score: 0, trend: 'stable', greenlit: true },
        frontend_qa: { status: 'unknown', failures: [] },
        swarm: { last_commit_sha: '', last_task: '', status: 'idle' },
        orchestrator: { next_action: 'none', reason: 'Initial state' }
    };
}

run();
