import { sovereignStorage } from '../swarm/core/storage.js';
import fs from 'fs/promises';
import path from 'path';
import { FileSystemTool } from '../swarm/tools/filesystem.js';
import { analyzeCapabilityGaps, inferIssuesFromState, readAgentRegistry } from './swarm_capability_analyzer.js';
import { generateAndRegisterAgent } from './swarm_agent_generator.js';
import {
    MAX_CHAIN_LENGTH,
    applyWorkflowCompletion,
    canDispatchAction,
    getAllowedNextStates,
    readSwarmMeta,
    readSwarmState,
    stateToAction,
    workflowToState
} from './swarm_state_machine.js';
import { evaluateSwarmHeartbeat } from './swarm_heartbeat.js';

interface SwarmState {
    last_updated: string;
    ci: { status: string; last_green_sha?: string; last_fail_reason?: string; build_duration?: string };
    curiosity: { findings: any[]; last_scan: string };
    evolution: { last_score: number; trend: string; greenlit: boolean };
    frontend_qa: { status: string; failures: any[] };
    swarm: { last_commit_sha: string; last_task: string; status: string };
    orchestrator: { next_action: string; reason: string };
}

async function run() {
    const mode = process.argv[2] || 'ORCHESTRATE';
    console.log(`🚀 [CI Manager] Mode: ${mode}`);

    try {
        // Pre-flight check: Verify Swarm path
        const swarmDir = path.resolve(process.cwd(), 'swarm');
        const stats = await fs.stat(swarmDir).catch(() => null);
        if (!stats) {
            throw new Error(`Swarm nucleus not found at ${swarmDir}. Ensure 'npm ci' was run in both root and swarm directories.`);
        }

        switch (mode) {
            case 'REPORT':
                await reportMetrics();
                break;
            case 'ORCHESTRATE':
                await orchestrate();
                break;
            case 'DASHBOARD':
                await generateDashboard();
                break;
            default:
                console.error(`Unknown mode: ${mode}`);
                process.exit(1)
        }
    } catch (err) {
        console.error(`❌ [CI Manager] Critical Failure:`, err);
        process.exit(1);
    }
}

/**
 * Generates the status dashboard (SWARM_STATUS.md)
 */
async function generateDashboard() {
    const wrapper = await sovereignStorage.load();
    const state = { ...createDefaultState(), ...(wrapper?.state || {}) } as SwarmState;
    const todo = await fs.readFile('TODO.md', 'utf8').catch(() => '');
    const swarmMemoryRaw = await fs.readFile(path.join('swarm', 'swarm_memory.json'), 'utf8').catch(() => '{}');
    const swarmMemory = JSON.parse(swarmMemoryRaw) as { empty_strategy_cycles?: number };
    const emptyStrategyCycles = swarmMemory.empty_strategy_cycles ?? 0;

    // Extract Phase Progress from TODO.md
    const phases = todo.match(/## (Phase \d+:[^ \n]+)/g) || [];
    const currentPhase = phases[phases.length - 1] || 'Phase 1: Stability';

    const md = `# AppForge Swarm Live Status
    
## 🚀 Current Engineering Phase
**${currentPhase}** (Synced from [TODO.md](TODO.md))

## 📊 Performance & Health
- **CI Status**: ${state.ci.status === 'pass' ? '✅ GREEN' : '❌ FAIL'}
- **Evolution Score**: ${state.evolution.last_score || 'N/A'}
- **Frontend QA**: ${state.frontend_qa.status || 'N/A'}

## 🧠 Strategic Oracle
- **Next Decision**: \`${state.orchestrator.next_action}\`
- **Logic Reason**: ${state.orchestrator.reason}

## 🏗️ Build Telemetry
- **Last Sync**: ${new Date(state.last_updated).toLocaleString()}
- **Build Dur**: ${state.ci.build_duration || 'N/A'}

## 🔁 Swarm Loop Telemetry
- **Empty Strategy Cycles**: ${emptyStrategyCycles}

---
*Status generated by Sovereign CI Manager*
`;

    await fs.writeFile('SWARM_STATUS.md', md);
    console.log('📝 [CI Manager] SWARM_STATUS.md updated.');
}

/**
 * Reports detailed metrics from a standard CI run (node.js.yml)
 */
async function reportMetrics() {
    const metricsPath = 'src/data/frontend_metrics.json';
    let metrics = { errorCount: 0, avgLatency: 0, lastFlush: new Date().toISOString(), topErrors: [] };

    try {
        const raw = await fs.readFile(metricsPath, 'utf8');
        metrics = JSON.parse(raw);
    } catch { }

    // In a real CI environment, we would parse test/lint results here
    // For now, we update the timestamp and basic health
    metrics.lastFlush = new Date().toISOString();

    await fs.writeFile(metricsPath, JSON.stringify(metrics, null, 2));
    console.log(`📊 [CI Manager] Telemetry reported to ${metricsPath}`);

    // Update Sovereign State via Upstash
    const wrapper = await sovereignStorage.load();
    const state = { ...createDefaultState(), ...(wrapper?.state || {}) } as SwarmState;

    state.ci = state.ci || ({} as any);
    state.ci.status = 'pass';
    state.ci.last_green_sha = process.env.GITHUB_SHA || '';
    await sovereignStorage.save({
        timestamp: new Date().toISOString(),
        version: '2.0.0',
        state: state
    });
}

/**
 * Handles the main orchestration loop formerly in Python
 */
async function orchestrate() {
    const fsTool = new FileSystemTool();
    const wrapper = await sovereignStorage.load();
    const state = { ...createDefaultState(), ...(wrapper?.state || {}) } as SwarmState;

    const trigger = process.env.TRIGGER || 'manual';
    const workflowName = process.env.WORKFLOW_NAME || '';
    const conclusion = process.env.CONCLUSION || '';
    const runId = process.env.RUN_ID || process.env.GITHUB_RUN_ID || 'local';
    const forceOverride = process.env.FORCE_OVERRIDE === 'true';

    console.log(`🧠 [CI Manager] Trigger: ${trigger} | Workflow: ${workflowName} | Conclusion: ${conclusion}`);

    const completion = await applyWorkflowCompletion({
        workflowName,
        runId,
        wasSuccessful: conclusion === 'success',
        forceOverride
    });

    if (completion.status === 'updated' && completion.telemetry) {
        console.log(JSON.stringify(completion.telemetry));
    } else if (completion.status === 'rejected') {
        console.warn('⚠️ [CI Manager] Invalid state detected while applying completion. State reset to IDLE.');
    }

    // PR67 architecture consolidation: CI manager no longer dispatches workflows directly.
    state.orchestrator = {
        next_action: 'none',
        reason: 'Dispatch logic disabled; swarm-loop.yml owns autonomous orchestration.'
    };
    state.last_updated = new Date().toISOString();
    await sovereignStorage.save({
        timestamp: new Date().toISOString(),
        version: '2.0.0',
        state
    });

    if (process.env.GITHUB_OUTPUT) {
        await fs.appendFile(process.env.GITHUB_OUTPUT, 'next_action=none\n');
        await fs.appendFile(process.env.GITHUB_OUTPUT, 'reason=swarm-loop controller is authoritative\n');
        await fs.appendFile(process.env.GITHUB_OUTPUT, 'dynamic_workflow=\n');
        await fs.appendFile(process.env.GITHUB_OUTPUT, 'task=swarm-loop controller is authoritative\n');
    }

    console.log('🎯 [CI Manager] Dispatch logic disabled in favor of swarm-loop controller.');
    return;

    const { record: swarmRecord, wasReset } = await readSwarmState(runId);
    const swarmMeta = await readSwarmMeta();

    if (wasReset) {
        console.warn('⚠️ [CI Manager] Swarm state was invalid and has been reset to IDLE.');
    }

    // 1. Merge Artifacts (if any)
    const artifactsDir = 'agent_outputs';
    try {
        const files = await fsTool.listFiles(`${artifactsDir}/**/*.json`);
        for (const file of files) {
            console.log(`   📂 Reading artifact: ${file}`);
            const data = JSON.parse(await fs.readFile(file, 'utf8'));
            const agentType = data.agent_type;
            if (agentType && (state as any)[agentType]) {
                console.log(`   📎 Merging artifact from ${agentType}`);
                Object.assign((state as any)[agentType], data.payload);
            }
        }
    } catch (err) {
        console.log('   ℹ️ No artifacts found or merge failed.');
    }

    // 2. Event Context Logic
    if (workflowName.includes('Node.js CI') || workflowName.includes('Iron Brain')) {
        state.ci.status = conclusion === 'success' ? 'pass' : 'fail';
        if (conclusion !== 'success') state.ci.last_fail_reason = `${workflowName} failed`;
    } else if (workflowName.includes('Frontend QA')) {
        state.frontend_qa.status = conclusion === 'success' ? 'pass' : 'fail';
    }

    // 3. Heartbeat Evaluation + Next Action Decision Matrix
    const heartbeat = await evaluateSwarmHeartbeat();

    let nextAction = 'none';
    let reason = 'All systems nominal';
    const forceAction = process.env.FORCE_ACTION || '';

    if (!forceAction && heartbeat.action === 'idle') {
        nextAction = 'none';
        reason = `Heartbeat idle: ${heartbeat.reason}`;
    } else if (!forceAction && swarmMeta.chain_length >= MAX_CHAIN_LENGTH) {
        nextAction = 'none';
        reason = `Workflow chain limit reached (${swarmMeta.chain_length}/${MAX_CHAIN_LENGTH}). Awaiting manual intervention.`;
    } else if (!forceAction && heartbeat.action !== 'idle') {
        nextAction = heartbeat.action;
        reason = `Heartbeat action: ${heartbeat.reason}`;
    } else {
        const allowedState = getAllowedNextStates(swarmRecord.state)[0];
        const stateMachineAction = allowedState ? stateToAction[allowedState] : 'none';

        if (forceAction) {
            const forceDecision = canDispatchAction({
                currentState: swarmRecord.state,
                requestedAction: forceAction,
                lastWorkflow: swarmMeta.last_workflow,
                forceOverride: true
            });
            nextAction = forceAction;
            reason = `Manually forced (${forceDecision.reason})`;
        } else {
            nextAction = stateMachineAction;
            reason = `State machine route: ${swarmRecord.state} → ${allowedState || 'none'}`;
        }
    }

    if (nextAction !== 'none') {
        const guard = canDispatchAction({
            currentState: swarmRecord.state,
            requestedAction: nextAction,
            lastWorkflow: swarmMeta.last_workflow,
            forceOverride: !!forceAction
        });

        if (!guard.allowed) {
            nextAction = 'none';
            reason = `Dispatch blocked by swarm state machine: ${guard.reason}`;
        }
    }

    if (!forceAction && conclusion === 'failure' && workflowToState[workflowName]) {
        nextAction = 'none';
        reason = `Workflow ${workflowName} failed. Awaiting retry/manual override.`;
    }

    const registry = await readAgentRegistry();
    const activeGoals = (process.env.SWARM_GOALS || '')
        .split(',')
        .map((goal) => goal.trim())
        .filter(Boolean);

    const issues = inferIssuesFromState({
        ciStatus: state.ci?.status,
        ciFailReason: state.ci?.last_fail_reason,
        frontendQaStatus: state.frontend_qa?.status,
        telemetryErrors: Number(process.env.TELEMETRY_ERRORS || 0)
    });

    const capabilityProposals = await analyzeCapabilityGaps(issues);
    let dynamicWorkflow = '';

    if (capabilityProposals.length > 0) {
        const generation = await generateAndRegisterAgent(capabilityProposals[0]);
        if (generation.created && generation.agent?.workflow) {
            registry.agents.push(generation.agent);
            console.log(JSON.stringify(generation.telemetry));
        } else if (generation.reason) {
            console.log(`ℹ️ [CI Manager] Dynamic agent creation skipped: ${generation.reason}`);
        }
    }

    if (!forceAction) {
        const dynamicAgent = registry.agents.find((agent) =>
            (agent.capabilities || []).some((capability) => activeGoals.includes(capability))
        );
        if (dynamicAgent) {
            nextAction = 'dynamic_agent';
            dynamicWorkflow = dynamicAgent.workflow;
            reason = `Dynamic dispatch selected: ${dynamicAgent.name}`;
        }
    }

    state.orchestrator = { next_action: nextAction, reason };
    state.last_updated = new Date().toISOString();

    // 4. Save State (Wrapped)
    await sovereignStorage.save({
        timestamp: new Date().toISOString(),
        version: '2.0.0',
        state: state
    });

    // 5. Output for GitHub Actions
    if (process.env.GITHUB_OUTPUT) {
        await fs.appendFile(process.env.GITHUB_OUTPUT, `next_action=${nextAction}\n`);
        await fs.appendFile(process.env.GITHUB_OUTPUT, `reason=${reason}\n`);
        await fs.appendFile(process.env.GITHUB_OUTPUT, `dynamic_workflow=${dynamicWorkflow}\n`);
        const taskDesc = nextAction === 'autonomous_swarm' ? `Fix: ${state.ci.last_fail_reason}` : reason;
        await fs.appendFile(process.env.GITHUB_OUTPUT, `task=${taskDesc}\n`);
    }

    console.log(`🎯 [CI Manager] Decision: ${nextAction} (${reason})`);
}

function createDefaultState(): SwarmState {
    return {
        last_updated: new Date().toISOString(),
        ci: { status: 'unknown' },
        curiosity: { findings: [], last_scan: '' },
        evolution: { last_score: 0, trend: 'stable', greenlit: true },
        frontend_qa: { status: 'unknown', failures: [] },
        swarm: { last_commit_sha: '', last_task: '', status: 'idle' },
        orchestrator: { next_action: 'none', reason: 'Initial state' }
    };
}

run();
