import { sovereignStorage } from '../swarm/core/storage.js';
import fs from 'fs/promises';
import path from 'path';
import { FileSystemTool } from '../swarm/tools/filesystem.js';
import {
    MAX_CHAIN_LENGTH,
    applyWorkflowCompletion,
    canDispatchAction,
    getAllowedNextStates,
    readSwarmMeta,
    readSwarmState,
    stateToAction,
    workflowToState
} from './swarm_state_machine.js';

interface SwarmState {
    last_updated: string;
    ci: { status: string; last_green_sha?: string; last_fail_reason?: string; build_duration?: string };
    curiosity: { findings: any[]; last_scan: string };
    evolution: { last_score: number; trend: string; greenlit: boolean };
    frontend_qa: { status: string; failures: any[] };
    swarm: { last_commit_sha: string; last_task: string; status: string };
    orchestrator: {
        next_action: string;
        reason: string;
        current_goal?: SwarmGoal;
        selected_workflow?: string;
        goal_action_history?: Array<{ goal: SwarmGoal; workflow: string; timestamp: string }>;
        telemetry?: GoalTelemetryEvent[];
    };
}

const WORKFLOW_ACTION_MAP: Record<string, string> = {
    'Autonomous Swarm Cycle': 'autonomous_swarm',
    'Quantum Self-Evolution': 'quantum_evolution',
    'Curiosity Engine Scan': 'curiosity_scan',
    'Frontend QA Swarm': 'frontend_qa_swarm',
    'Iron Brain CI — Ghost Brain': 'autonomous_swarm',
    'Evolution Benchmark Gate': 'quantum_evolution'
};

async function run() {
    const mode = process.argv[2] || 'ORCHESTRATE';
    console.log(`🚀 [CI Manager] Mode: ${mode}`);

    try {
        // Pre-flight check: Verify Swarm path
        const swarmDir = path.resolve(process.cwd(), 'swarm');
        const stats = await fs.stat(swarmDir).catch(() => null);
        if (!stats) {
            throw new Error(`Swarm nucleus not found at ${swarmDir}. Ensure 'npm ci' was run in both root and swarm directories.`);
        }

        switch (mode) {
            case 'REPORT':
                await reportMetrics();
                break;
            case 'ORCHESTRATE':
                await orchestrate();
                break;
            case 'DASHBOARD':
                await generateDashboard();
                break;
            default:
                console.error(`Unknown mode: ${mode}`);
                process.exit(1)
        }
    } catch (err) {
        console.error(`❌ [CI Manager] Critical Failure:`, err);
        process.exit(1);
    }
}

/**
 * Generates the status dashboard (SWARM_STATUS.md)
 */
async function generateDashboard() {
    const wrapper = await sovereignStorage.load();
    const state = { ...createDefaultState(), ...(wrapper?.state || {}) } as SwarmState;
    const todo = await fs.readFile('TODO.md', 'utf8').catch(() => '');

    // Extract Phase Progress from TODO.md
    const phases = todo.match(/## (Phase \d+:[^ \n]+)/g) || [];
    const currentPhase = phases[phases.length - 1] || 'Phase 1: Stability';

    const md = `# AppForge Swarm Live Status
    
## 🚀 Current Engineering Phase
**${currentPhase}** (Synced from [TODO.md](TODO.md))

## 📊 Performance & Health
- **CI Status**: ${state.ci.status === 'pass' ? '✅ GREEN' : '❌ FAIL'}
- **Evolution Score**: ${state.evolution.last_score || 'N/A'}
- **Frontend QA**: ${state.frontend_qa.status || 'N/A'}

## 🧠 Strategic Oracle
- **Next Decision**: \`${state.orchestrator.next_action}\`
- **Logic Reason**: ${state.orchestrator.reason}

## 🏗️ Build Telemetry
- **Last Sync**: ${new Date(state.last_updated).toLocaleString()}
- **Build Dur**: ${state.ci.build_duration || 'N/A'}

---
*Status generated by Sovereign CI Manager*
`;

    await fs.writeFile('SWARM_STATUS.md', md);
    console.log('📝 [CI Manager] SWARM_STATUS.md updated.');
}

/**
 * Reports detailed metrics from a standard CI run (node.js.yml)
 */
async function reportMetrics() {
    const metricsPath = 'src/data/frontend_metrics.json';
    let metrics = { errorCount: 0, avgLatency: 0, lastFlush: new Date().toISOString(), topErrors: [] };

    try {
        const raw = await fs.readFile(metricsPath, 'utf8');
        metrics = JSON.parse(raw);
    } catch { }

    // In a real CI environment, we would parse test/lint results here
    // For now, we update the timestamp and basic health
    metrics.lastFlush = new Date().toISOString();

    await fs.writeFile(metricsPath, JSON.stringify(metrics, null, 2));
    console.log(`📊 [CI Manager] Telemetry reported to ${metricsPath}`);

    // Update Sovereign State via Upstash
    const wrapper = await sovereignStorage.load();
    const state = { ...createDefaultState(), ...(wrapper?.state || {}) } as SwarmState;

    state.ci = state.ci || ({} as any);
    state.ci.status = 'pass';
    state.ci.last_green_sha = process.env.GITHUB_SHA || '';
    await sovereignStorage.save({
        timestamp: new Date().toISOString(),
        version: '2.0.0',
        state: state
    });
}

/**
 * Handles the main orchestration loop formerly in Python
 */
async function orchestrate() {
    const fsTool = new FileSystemTool();
    const wrapper = await sovereignStorage.load();
    const state = { ...createDefaultState(), ...(wrapper?.state || {}) } as SwarmState;

    const trigger = process.env.TRIGGER || 'manual';
    const workflowName = process.env.WORKFLOW_NAME || '';
    const conclusion = process.env.CONCLUSION || '';
    const runId = process.env.RUN_ID || process.env.GITHUB_RUN_ID || 'local';
    const forceOverride = process.env.FORCE_OVERRIDE === 'true';

    console.log(`🧠 [CI Manager] Trigger: ${trigger} | Workflow: ${workflowName} | Conclusion: ${conclusion}`);

    const completion = await applyWorkflowCompletion({
        workflowName,
        runId,
        wasSuccessful: conclusion === 'success',
        forceOverride
    });

    if (completion.status === 'updated' && completion.telemetry) {
        console.log(JSON.stringify(completion.telemetry));
    } else if (completion.status === 'rejected') {
        console.warn('⚠️ [CI Manager] Invalid state detected while applying completion. State reset to IDLE.');
    }

    const { record: swarmRecord, wasReset } = await readSwarmState(runId);
    const swarmMeta = await readSwarmMeta();

    if (wasReset) {
        console.warn('⚠️ [CI Manager] Swarm state was invalid and has been reset to IDLE.');
    }

    // 1. Merge Artifacts (if any)
    const artifactsDir = 'agent_outputs';
    try {
        const files = await fsTool.listFiles(`${artifactsDir}/**/*.json`);
        for (const file of files) {
            console.log(`   📂 Reading artifact: ${file}`);
            const data = JSON.parse(await fs.readFile(file, 'utf8'));
            const agentType = data.agent_type;
            if (agentType && (state as any)[agentType]) {
                console.log(`   📎 Merging artifact from ${agentType}`);
                Object.assign((state as any)[agentType], data.payload);
            }
        }
    } catch (err) {
        console.log('   ℹ️ No artifacts found or merge failed.');
    }

    // 2. Event Context Logic
    if (workflowName.includes('Node.js CI') || workflowName.includes('Iron Brain')) {
        state.ci.status = conclusion === 'success' ? 'pass' : 'fail';
        if (conclusion !== 'success') state.ci.last_fail_reason = `${workflowName} failed`;
    } else if (workflowName.includes('Frontend QA')) {
        state.frontend_qa.status = conclusion === 'success' ? 'pass' : 'fail';
    }

    // 3. Decide Next Action (Goal-Driven Decision Matrix)
    const telemetryEvents = Array.isArray(state.orchestrator?.telemetry) ? state.orchestrator.telemetry : [];
    const recentCommits = await readRecentCommits();

    const selectedGoal = await determine_current_goal({
        ciStatus: state.ci.status,
        frontendQaStatus: state.frontend_qa.status,
        benchmarkTrend: state.evolution.trend,
        benchmarkScore: state.evolution.last_score,
        lastUpdated: state.last_updated,
        recentCommits,
        telemetryEvents: telemetryEvents.map((event) => ({ type: event.type, timestamp: event.timestamp }))
    });

    const storedGoal = await loadStoredGoal();
    const goalState = await saveGoalState(selectedGoal, storedGoal?.goal === selectedGoal ? storedGoal.priority : 1);

    const goalActionHistory = Array.isArray(state.orchestrator?.goal_action_history)
        ? state.orchestrator.goal_action_history
        : [];

    const recentGoalActions = goalActionHistory
        .filter((entry) => entry.goal === selectedGoal)
        .slice(-5)
        .map((entry) => entry.workflow);

    let nextAction = 'none';
    let reason = 'All systems nominal';
    const forceAction = process.env.FORCE_ACTION || '';

    if (!forceAction && swarmMeta.chain_length >= MAX_CHAIN_LENGTH) {
        reason = `Workflow chain limit reached (${swarmMeta.chain_length}/${MAX_CHAIN_LENGTH}). Awaiting manual intervention.`;
    } else {
        const allowedState = getAllowedNextStates(swarmRecord.state)[0];
        const stateMachineAction = allowedState ? stateToAction[allowedState] : 'none';

        if (forceAction) {
            const forceDecision = canDispatchAction({
                currentState: swarmRecord.state,
                requestedAction: forceAction,
                lastWorkflow: swarmMeta.last_workflow,
                forceOverride: true
            });
            nextAction = forceAction;
            reason = `Manually forced (${forceDecision.reason})`;
        } else {
            nextAction = stateMachineAction;
            reason = `State machine route: ${swarmRecord.state} → ${allowedState || 'none'}`;
        }
    }

    if (nextAction !== 'none') {
        const guard = canDispatchAction({
            currentState: swarmRecord.state,
            requestedAction: nextAction,
            lastWorkflow: swarmMeta.last_workflow,
            forceOverride: !!forceAction
        });

        if (!guard.allowed) {
            nextAction = 'none';
            reason = `Dispatch blocked by swarm state machine: ${guard.reason}`;
        }
    }

    if (!forceAction && nextAction === 'none' && trigger === 'schedule' && swarmRecord.state === 'IDLE') {
        nextAction = 'curiosity_scan';
        reason = 'Scheduled curiosity pulse from IDLE';
    }

    if (!forceAction && conclusion === 'failure' && workflowToState[workflowName]) {
        nextAction = 'none';
        reason = `Workflow ${workflowName} failed. Awaiting retry/manual override.`;
    }

    const telemetry: GoalTelemetryEvent[] = [
        {
            type: 'swarm_goal_selected',
            goal: selectedGoal,
            timestamp: new Date().toISOString(),
            details: { priority: goalState.priority }
        },
        {
            type: 'swarm_action_selected',
            goal: selectedGoal,
            selected_workflow: selectedWorkflow,
            timestamp: new Date().toISOString(),
            details: { next_action: nextAction }
        },
        {
            type: 'swarm_action_executed',
            goal: selectedGoal,
            selected_workflow: selectedWorkflow,
            timestamp: new Date().toISOString(),
            details: { dispatched: nextAction !== 'none', trigger }
        }
    ];

    if (selectedWorkflow) {
        goalActionHistory.push({
            goal: selectedGoal,
            workflow: selectedWorkflow,
            timestamp: new Date().toISOString()
        });
    }

    state.orchestrator = {
        ...state.orchestrator,
        next_action: nextAction,
        reason,
        current_goal: selectedGoal,
        selected_workflow: selectedWorkflow,
        goal_action_history: goalActionHistory.slice(-30),
        telemetry: [...telemetryEvents, ...telemetry].slice(-50)
    };
    state.last_updated = new Date().toISOString();

    // 4. Save State (Wrapped)
    await sovereignStorage.save({
        timestamp: new Date().toISOString(),
        version: '2.0.0',
        state: state
    });

    // 5. Output for GitHub Actions
    if (process.env.GITHUB_OUTPUT) {
        await fs.appendFile(process.env.GITHUB_OUTPUT, `next_action=${nextAction}\n`);
        await fs.appendFile(process.env.GITHUB_OUTPUT, `reason=${reason}\n`);
        await fs.appendFile(process.env.GITHUB_OUTPUT, `current_goal=${selectedGoal}\n`);
        await fs.appendFile(process.env.GITHUB_OUTPUT, `selected_workflow=${selectedWorkflow}\n`);
        const taskDesc = nextAction === 'autonomous_swarm' ? `Fix: ${state.ci.last_fail_reason}` : reason;
        await fs.appendFile(process.env.GITHUB_OUTPUT, `task=${taskDesc}\n`);
    }

    console.log(`🎯 [CI Manager] Goal: ${selectedGoal} | Workflow: ${selectedWorkflow || 'none'} | Decision: ${nextAction} (${reason})`);
}

function createDefaultState(): SwarmState {
    return {
        last_updated: new Date().toISOString(),
        ci: { status: 'unknown' },
        curiosity: { findings: [], last_scan: '' },
        evolution: { last_score: 0, trend: 'stable', greenlit: true },
        frontend_qa: { status: 'unknown', failures: [] },
        swarm: { last_commit_sha: '', last_task: '', status: 'idle' },
        orchestrator: { next_action: 'none', reason: 'Initial state' }
    };
}

async function readRecentCommits(): Promise<string[]> {
    try {
        const { execFile } = await import('node:child_process');
        const { promisify } = await import('node:util');
        const execFileAsync = promisify(execFile);
        const { stdout } = await execFileAsync('git', ['log', '--pretty=%s', '-5']);
        return stdout
            .split('\n')
            .map((line) => line.trim())
            .filter(Boolean);
    } catch {
        return [];
    }
}

function invertActionLookup(action: string): string | undefined {
    const entry = Object.entries(WORKFLOW_ACTION_MAP).find(([, mappedAction]) => mappedAction === action);
    return entry?.[0];
}

run();
