import { execSync } from 'child_process';

const token = process.env.GITHUB_TOKEN;
const repo = process.env.GITHUB_REPOSITORY;

if (!token || !repo) {
    console.error('❌ [Evolution PR] Missing GITHUB_TOKEN or GITHUB_REPOSITORY');
    process.exit(1);
}

const [owner, name] = repo.split('/');
const timestamp = Date.now();
const branch = `swarm-evolution-${timestamp}`;

function run(cmd: string) {
    console.log(`Executing: ${cmd}`);
    execSync(cmd, { stdio: 'inherit' });
}

async function createPR() {
    console.log(`🚀 [Evolution PR] Creating branch: ${branch}`);

    try {
        run(`git checkout -b ${branch}`);
        run(`git add .`);

        // Final sanity check on what we are committing
        const status = execSync('git status --porcelain', { encoding: 'utf8' });
        if (!status) {
            console.log('🤷 [Evolution PR] No changes to commit. Aborting.');
            return;
        }

        run(`git commit -m "auto: swarm evolution cycle"`);
        run(`git push origin ${branch}`);

        console.log(`📡 [Evolution PR] Opening Pull Request for ${repo}...`);

        const response = await fetch(
            `https://api.github.com/repos/${owner}/${name}/pulls`,
            {
                method: 'POST',
                headers: {
                    Authorization: `Bearer ${token}`,
                    'Accept': 'application/vnd.github.v3+json',
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    title: '🌀 Swarm Evolution Cycle',
                    head: branch,
                    base: 'main',
                    body: `### 🔱 Autonomous Mutation Cycle\n\nThis PR was generated by the God Swarm evolution loop.\n\n- **Cycle Timestamp**: ${new Date(timestamp).toISOString()}\n- **Origin Node**: ${process.env.NODE_ID || 'Unknown'}\n\nPlease review and merge if the metrics show improvement.`
                })
            }
        );

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`Failed to create PR: ${errorText}`);
        }

        const prData: any = await response.json();
        console.log(`✅ [Evolution PR] PR created successfully: ${prData.html_url}`);
    } catch (error: any) {
        console.error('❌ [Evolution PR] Error:', error.message);
        process.exit(1);
    }
}

createPR();
